default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 10
  timeout: 3000
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  database: <%= "simple_chat_#{Rails.env.downcase}" %>

development:
  <<: *mysql

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
